# Generated by Django 6.0.2 on 2026-03-03 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issuedecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='issuedecision',
            constraint=models.UniqueConstraint(fields=('issue',), name='uniq_one_decision_per_issue'),
        ),
    ]
