# Generated by Django 6.0.2 on 2026-03-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issuedecision_uniq_one_decision_per_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='hod_notes',
            field=models.TextField(blank=True, help_text='Final decision notes from the process'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to HOD'), ('HOD_APPROVED', 'HOD Approved (Pending Faculty Board)'), ('DEAN_APPROVED', 'Dean Approved (Pending Deans Committee)'), ('FINAL_APPROVED', 'Final Approval (Rector)'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for Revision')], default='DRAFT', max_length=20),
        ),
    ]
