# Generated by Django 6.0.2 on 2026-04-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_hod_notes_alter_issue_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='issuedecision',
            name='uniq_one_decision_per_issue',
        ),
        migrations.AddField(
            model_name='issue',
            name='dean_notes',
            field=models.TextField(blank=True, help_text='Dean decision notes from the process'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to HOD'), ('HOD_APPROVED', 'HOD Approved (Pending Faculty Board)'), ('DEAN_APPROVED', 'Dean Approved (Pending Deans Committee)'), ('FINAL_APPROVED', 'Final Approval (Rector)'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for Revision'), ('RETURNED_TO_HOD', 'Returned to HOD for Revision')], default='DRAFT', max_length=20),
        ),
    ]
