# Generated by Django 6.0.2 on 2026-04-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_remove_issuedecision_uniq_one_decision_per_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='rector_notes',
            field=models.TextField(blank=True, help_text='Rector decision notes from the process'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted to HOD'), ('HOD_APPROVED', 'HOD Approved (Pending Faculty Board)'), ('DEAN_APPROVED', 'Dean Approved (Pending Deans Committee)'), ('FINAL_APPROVED', 'Final Approval (Rector)'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for Revision'), ('RETURNED_TO_HOD', 'Returned to HOD for Revision'), ('RETURNED_TO_DEAN', 'Returned to Dean for Revision')], default='DRAFT', max_length=20),
        ),
    ]
