# Generated by Django 6.0.2 on 2026-06-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_issuehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
