# Generated by Django 6.0.2 on 2026-03-06 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_department_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'faculty')},
        ),
    ]
