# Generated by Django 6.0.2 on 2026-04-19 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_department_unique_together'),
        ('issues', '0006_issue_rector_notes_alter_issue_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('BOS', 'Board of Studies'), ('BOF', 'Board of Faculty')], default='BOS', max_length=3)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('minutes_attachment', models.FileField(blank=True, null=True, upload_to='meeting_minutes/')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONCLUDED', 'Concluded'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda_issues', models.ManyToManyField(blank=True, related_name='meetings', to='issues.issue')),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_meetings', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Required for BOS meetings.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bos_meetings', to='core.department')),
                ('faculty', models.ForeignKey(blank=True, help_text='Required for BOF meetings.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bof_meetings', to='core.faculty')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
