# Generated by Django 6.0.2 on 2026-06-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('BOS', 'Board of Studies'), ('BOF', 'Board of Faculty'), ('DCM', 'Deans Committee Meeting')], default='BOS', max_length=3),
        ),
    ]
